services:
  
  notification_service:
    build:
      context: .
      dockerfile: NotificationService/NotificationService.API/Dockerfile
    container_name: notification_service_container
    ports:
      - "5003:80"
    environment:
      - ConnectionStrings__DefaultConnection=Host=case_study_postgres;Port=5432;Database=notification_db;Username=postgres;Password=postgres
      - RabbitMQ__Hostname=case_study_rabbitmq
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
    depends_on:
      - case_study_postgres
      - case_study_rabbitmq
    restart: always
  
  order_service:
    build:
      context: .
      dockerfile: OrderService/OrderService.API/Dockerfile
    container_name: order_service_container
    ports:
      - "5002:80"
    environment:
      - ConnectionStrings__DefaultConnection=Host=case_study_postgres;Port=5432;Database=order_db;Username=postgres;Password=postgres
      - RabbitMQ__Hostname=case_study_rabbitmq
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
    depends_on:
      - case_study_postgres
      - case_study_rabbitmq
    restart: always
      
  stock_service:
    build:
      context: .
      dockerfile: StockService/StockService.API/Dockerfile
    container_name: stock_service_container
    ports:
      - "5001:80"
    environment:
      - ConnectionStrings__DefaultConnection=Host=case_study_postgres;Port=5432;Database=stock_db;Username=postgres;Password=postgres
      - RabbitMQ__Hostname=case_study_rabbitmq
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
    depends_on:
      - case_study_postgres
      - case_study_rabbitmq
    restart: always

  case_study_postgres:
    container_name: case_study_postgres
    image: postgres:13
    ports:
      - "5532:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  case_study_rabbitmq:
    container_name: case_study_rabbitmq
    image: rabbitmq:3-management
    ports:
      - "16672:15672"
      - "5772:5672"